# action.yml
name: 'Read changelog'
description: 'Reading changelog from file'
inputs:
  changelogfile:
    description: 'File for handling'
    required: true
    default: 'none'
  tag:  # id of input
    description: 'Search tag'
    required: true
    default: 'none'
outputs:
  content: # id of output
    description: 'Changelog for search tag'
runs:
  using: 'docker'
  image: 'docker://sergeyladanov/read-changelog-ci:v1'
  args:
    - -f
    - ${{ inputs.changelogfile }}
    - -t
    - ${{ inputs.tag }}
